name: Utician
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  shared_preferences: ^0.5.4+3
  flutter_swiper : ^1.1.6
  connectivity: ^0.4.5+3
  android_intent: ^0.3.4+4
  get_version: ^0.2.0+1
  flutter_auth_buttons: ^0.6.0



  # The following adds the Cupertino Icons font to your application.

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/makeup1.jpg
   - assets/images/icon.png
   - assets/images/icononboard.png
   - assets/images/icon2.jpg
   - assets/images/icon3.png
   - assets/images/login.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DancingScript-Regular
      fonts:
        - asset: assets/fonts/DancingScript-Regular.otf
    - family: AvenirNextLTProBold
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
    - family: AvernirNextLTProBoldCN
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-BoldCn.otf
    - family: AvernirNextLTProMediumCN
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-MediumCn.otf
    - family: AvenirNextLTProRegular
      fonts:  
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
    - family: UbuntuBold
      fonts:
        - asset: assets/fonts/Ubuntu-B.ttf
    - family: UbuntuBoldItalic
      fonts:
        - asset: assets/fonts/Ubuntu-BI.ttf
    - family: UbuntuCondensed
      fonts:
        - asset: assets/fonts/Ubuntu-C.ttf        
    - family: UbuntuLight
      fonts:
        - asset: assets/fonts/Ubuntu-L.ttf
    - family: UbuntuLightItalic
      fonts:
        - asset: assets/fonts/Ubuntu-L.ttf
    - family: UbuntuMedium
      fonts:
        - asset: assets/fonts/Ubuntu-M.ttf
    - family: UbuntuMediumItalic
      fonts:
        - asset: assets/fonts/Ubuntu-MI.ttf
    - family: UbuntuRegular
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
    - family: UbuntuRegularItalic
      fonts:
        - asset: assets/fonts/Ubuntu-RI.ttf
    - family: UbuntuMonoBold
      fonts:
        - asset: assets/fonts/UbuntuMono-B.ttf
    - family: UbuntuMonoBoldItalic
      fonts:
        - asset: assets/fonts/UbuntuMono-BI.ttf 
    - family: UbuntuMonoRegular
      fonts:
        - asset: assets/fonts/UbuntuMono-R.ttf
    - family: UbuntuMonoRegularItalic
      fonts:
        - asset: assets/fonts/UbuntuMono-RI.ttf          
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
